.\"
.\"   $Id: lshell.1,v 1.7 2009-01-26 00:09:55 ghantoos Exp $
.\"
.\"   Man page for the Limited Shell (lshell) project.
.\"
.TH LSHELL 1 "January 25, 2009" "v0.2.4" "USER COMMANDS"

.SH NAME
lshell \- Limited Shell

.SH SYNOPSIS
.B lshell 
[\fIOPTION\fR] [\fIFILE\fR]

.SH DESCRIPTION
\fBlshell\fR provides a limited shell configured per user.
The configuration is done quite simply using a configuration file.
Coupled with ssh's 
.I authorized_keys 
or with
.I /etc/shells
and 
.I /etc/passwd
, it becomes very easy to restrict user's access to a limited set of command.

.SH OPTIONS
.TP
.B \--config=\fIFILE\fR
Select config file (default is /etc/lshell.conf)
.TP
.B \--log=\fIFILE\fR
Specify the log file to use
.TP
.B \-h, --help
Show help message
.TP
.B \--version
Show version

.SH EXAMPLES
.TP
.B $ lshell
.RS
Tries to un lshell using default /etc/lshell.conf as configuration file. If it 
fails a warning is printed and lshell is interrupted.
Tries to un lshell using default /var/log/lshell.conf as log file. If it fails
a warning is printed and lshell is continues runing.
.RE
.TP
.B $ lshell --config /path/to/myconf.file --log /path/to/mylog.log
.RS
This will override the default options specified for configuration and/or log file
.RE

.SH TODO
.TP
In order to log a user's warnings into the default \fI/var/log/lshell.log\fR file, you must add the user to the \fIlshellg\fR group:

$ usermod -G lshellg user_name
.TP
In order to set lshell as default shell for a user:

$ chsh -s /usr/bin/lshell user_name

.SH AUTHOR
Currently maintained by Ignace Mouzannar -ghantoos- 

.SH EMAIL
Feel free to send me your recommendations at <ghantoos@ghantoos.org>
