#!/bin/sh
#
# $Id: postinstall,v 1.2 2008-10-30 15:42:01 ghantoos Exp $
#
# RPM build postinstall script

groupadd lshellg
chown root:lshellg /var/log/lshell.log
chmod 664 /var/log/lshell.log


#####
# This part is taken from debian `add-shell` script
#####

lshell=/usr/bin/lshell
file=/etc/shells
tmpfile=${file}.tmp

set -o noclobber

trap "rm -f ${tmpfile}" EXIT

if ! cat ${file} > ${tmpfile}
then
        cat 1>&2 <<EOF
Either another instance of $0 is running, or it was previously interrupted.
Please examine ${tmpfile} to see if it should be moved onto ${file}.
EOF
        exit 1
fi


if ! grep -q "^${lshell}" ${tmpfile}
then
	echo ${lshell} >> ${tmpfile}
fi
chmod --reference=${file} ${tmpfile}
chown --reference=${file} ${tmpfile}

mv ${tmpfile} ${file}

trap "" EXIT
exit 0
