#!/bin/sh
#
# $Id: preinstall,v 1.2 2009-02-15 18:46:58 ghantoos Exp $
#
# RPM build preinstall script

# Save the configuration
if [ -f "/etc/lshell.conf" ]; then
    cp /etc/lshell.conf /etc/lshell.conf-preinstall
fi

exit 0
