#!/bin/sh
# RPM pre-install hook for lshell

set -eu

# Keep a backup of an existing config prior to upgrade/install.
if [ -f /etc/lshell.conf ]; then
    cp -a /etc/lshell.conf /etc/lshell.conf-preinstall
fi

exit 0
