#!/bin/sh
#
# $Id: preinstall,v 1.1 2009-01-27 14:36:43 ghantoos Exp $
#
# RPM build preinstall script

# Save the configuration
if [ -f "/etc/lshell.conf" ]; then
	mv /etc/lshell.conf /etc/lshell.conf-preinstall
fi

exit 0
