#!/bin/sh
# postinst script for lshell
#
# $Id: postinst,v 1.4 2008-10-20 20:27:36 ghantoos Exp $
#

set -e

case "$1" in
    configure)
	# add lshell group, and make it own the default log file
	groupadd lshellg
	chown root:lshellg /var/log/lshell.log
	chmod 664 /var/log/lshell.log
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


