#!/bin/sh
# postrm script for lshell
#
# $Id: prerm,v 1.4 2008-10-25 14:22:05 ghantoos Exp $
#

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	# delete lshell group
	groupdel lshellg
	pycentral pkgremove lshell
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


