#!/bin/sh
# postrm script for lshell
#
# $Id
#

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	# delete lshell group
	groupdel lshell
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


