#!/bin/sh
# postrm script for lshell
#
# $Id: prerm,v 1.6 2008-12-04 22:37:58 ghantoos Exp $
#

#DEBHELPER#

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	# delete lshell group
	groupdel lshellg
	pycentral pkgremove lshell
	/usr/sbin/remove-shell /usr/bin/lshell 
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


