[lshell_target]
lshell-ssh-target ansible_host=lshell-ssh-target ansible_port=22 ansible_user=root ansible_password=rootpass ansible_connection=ssh ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
